# Generated by Django 3.0.3 on 2020-02-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=12)),
                ('university', models.CharField(max_length=100)),
                ('adviser', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
    ]
