# Generated by Django 3.0.3 on 2020-02-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
